import { v4 as uuid } from 'uuid';
import type {
  Task,
  Project,
  CalendarEvent,
  TimeSession,
  Idea,
  Board,
  Activity,
  UserSettings,
} from '../types';
import { format, addDays } from 'date-fns';
import { todayISO } from '../lib/date';

// Deterministic-ish seed data so the app never feels empty on first run.
// Dates are computed relative to "today" at seed time, in LOCAL time —
// matching lib/date.ts's todayISO() so "today" never drifts a day off
// near midnight in timezones ahead of/behind UTC.

const today = todayISO();
const iso = (offsetDays: number) => format(addDays(new Date(), offsetDays), 'yyyy-MM-dd');

export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj-teopm',
    name: 'TEOPM',
    description: 'Marketing campaign, landing page and content push.',
    status: 'Active',
    color: '#8b5cf6',
    icon: '◭',
    createdAt: iso(-40),
  },
  {
    id: 'proj-wms',
    name: 'WMS',
    description: 'Branding & identity — logo, type system, colors.',
    status: 'On Track',
    color: '#3b82f6',
    icon: '▤',
    createdAt: iso(-30),
  },
  {
    id: 'proj-personal',
    name: 'Personal',
    description: 'Everything that keeps the human running.',
    status: 'Active',
    color: '#22c55e',
    icon: '●',
    createdAt: iso(-90),
  },
  {
    id: 'proj-michiverso',
    name: 'Michiverso',
    description: 'Blindboxes & merch universe.',
    status: 'At Risk',
    color: '#ec4899',
    icon: '✚',
    createdAt: iso(-15),
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Diseñar logo WMS',
    description: 'Explorar 3 direcciones tipográficas para el logo principal.',
    projectId: 'proj-wms',
    category: 'Design',
    priority: 'High',
    status: 'In Progress',
    dueDate: today,
    dueTime: '11:30',
    estimatedMinutes: 120,
    actualMinutes: 45,
    tags: ['logo', 'branding'],
    createdAt: iso(-3),
    completedAt: null,
    updatedAt: iso(-1),
  },
  {
    id: 'task-2',
    title: 'Actualizar landing TEOPM',
    description: 'Nueva sección hero + formulario de contacto.',
    projectId: 'proj-teopm',
    category: 'Marketing',
    priority: 'High',
    status: 'In Progress',
    dueDate: today,
    dueTime: '10:00',
    estimatedMinutes: 180,
    actualMinutes: 90,
    tags: ['landing', 'copy'],
    createdAt: iso(-2),
    completedAt: null,
    updatedAt: iso(-1),
  },
  {
    id: 'task-3',
    title: 'Reunión con Pao',
    description: 'Sync semanal de proyectos activos.',
    projectId: 'proj-teopm',
    category: 'Meetings',
    priority: 'Medium',
    status: 'Today',
    dueDate: today,
    dueTime: '15:00',
    estimatedMinutes: 60,
    actualMinutes: 0,
    tags: [],
    createdAt: iso(-1),
    completedAt: null,
    updatedAt: iso(-1),
  },
  {
    id: 'task-4',
    title: 'Revisar campaña LinkedIn',
    description: 'Feedback sobre creativos y copy de la campaña de septiembre.',
    projectId: 'proj-teopm',
    category: 'Marketing',
    priority: 'Medium',
    status: 'To Do',
    dueDate: today,
    dueTime: null,
    estimatedMinutes: 60,
    actualMinutes: 0,
    tags: ['linkedin'],
    createdAt: iso(-1),
    completedAt: null,
    updatedAt: iso(-1),
  },
  {
    id: 'task-5',
    title: 'Actualizar presentación',
    description: 'Slides con avances del mes para stakeholders.',
    projectId: null,
    category: 'Admin',
    priority: 'Low',
    status: 'To Do',
    dueDate: today,
    dueTime: '17:00',
    estimatedMinutes: 60,
    actualMinutes: 0,
    tags: [],
    createdAt: iso(-1),
    completedAt: null,
    updatedAt: iso(-1),
  },
  {
    id: 'task-6',
    title: 'Ideas para stream',
    description: 'Brainstorm de segmentos para el próximo stream.',
    projectId: 'proj-personal',
    category: 'Content',
    priority: 'Low',
    status: 'To Do',
    dueDate: today,
    dueTime: null,
    estimatedMinutes: 30,
    actualMinutes: 0,
    tags: ['stream'],
    createdAt: iso(0),
    completedAt: null,
    updatedAt: iso(0),
  },
  {
    id: 'task-7',
    title: 'Exportar assets de marca WMS',
    description: 'PNG/SVG del logo final en todas las variantes.',
    projectId: 'proj-wms',
    category: 'Design',
    priority: 'Medium',
    status: 'Done',
    dueDate: iso(-2),
    dueTime: null,
    estimatedMinutes: 45,
    actualMinutes: 50,
    tags: ['export'],
    createdAt: iso(-6),
    completedAt: iso(-2),
    updatedAt: iso(-2),
  },
  {
    id: 'task-8',
    title: 'Definir paleta de color WMS',
    description: '',
    projectId: 'proj-wms',
    category: 'Design',
    priority: 'Medium',
    status: 'Done',
    dueDate: iso(-5),
    dueTime: null,
    estimatedMinutes: 60,
    actualMinutes: 55,
    tags: [],
    createdAt: iso(-8),
    completedAt: iso(-5),
    updatedAt: iso(-5),
  },
  {
    id: 'task-9',
    title: 'Calendario de contenido TEOPM — Q4',
    description: '',
    projectId: 'proj-teopm',
    category: 'Marketing',
    priority: 'High',
    status: 'Done',
    dueDate: iso(-4),
    dueTime: null,
    estimatedMinutes: 90,
    actualMinutes: 100,
    tags: [],
    createdAt: iso(-10),
    completedAt: iso(-4),
    updatedAt: iso(-4),
  },
  {
    id: 'task-10',
    title: 'Grabar audio para reel TEOPM',
    description: '',
    projectId: 'proj-teopm',
    category: 'Content',
    priority: 'Medium',
    status: 'Done',
    dueDate: iso(-3),
    dueTime: null,
    estimatedMinutes: 40,
    actualMinutes: 35,
    tags: [],
    createdAt: iso(-7),
    completedAt: iso(-3),
    updatedAt: iso(-3),
  },
  {
    id: 'task-11',
    title: 'Sketch de personajes Michiverso',
    description: '',
    projectId: 'proj-michiverso',
    category: 'Design',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: iso(1),
    dueTime: null,
    estimatedMinutes: 120,
    actualMinutes: 20,
    tags: ['art'],
    createdAt: iso(-2),
    completedAt: null,
    updatedAt: iso(-1),
  },
  {
    id: 'task-12',
    title: 'Investigar proveedores de blindbox',
    description: '',
    projectId: 'proj-michiverso',
    category: 'Admin',
    priority: 'Low',
    status: 'To Do',
    dueDate: iso(2),
    dueTime: null,
    estimatedMinutes: 60,
    actualMinutes: 0,
    tags: [],
    createdAt: iso(-1),
    completedAt: null,
    updatedAt: iso(-1),
  },
  {
    id: 'task-13',
    title: 'Meditar / journaling',
    description: '',
    projectId: 'proj-personal',
    category: 'Personal',
    priority: 'Low',
    status: 'Done',
    dueDate: iso(-1),
    dueTime: null,
    estimatedMinutes: 20,
    actualMinutes: 20,
    tags: [],
    createdAt: iso(-1),
    completedAt: iso(-1),
    updatedAt: iso(-1),
  },
  {
    id: 'task-14',
    title: 'Organizar finanzas del mes',
    description: '',
    projectId: 'proj-personal',
    category: 'Personal',
    priority: 'Medium',
    status: 'Review',
    dueDate: iso(1),
    dueTime: null,
    estimatedMinutes: 45,
    actualMinutes: 15,
    tags: [],
    createdAt: iso(-2),
    completedAt: null,
    updatedAt: iso(-1),
  },
];

export const SEED_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'TEOPM Marketing Campaign',
    date: today,
    startTime: '10:00',
    endTime: '11:30',
    color: '#8b5cf6',
    taskId: 'task-2',
    projectId: 'proj-teopm',
    source: 'local',
  },
  {
    id: 'evt-2',
    title: 'Logo WMS',
    date: today,
    startTime: '11:30',
    endTime: '13:00',
    color: '#3b82f6',
    taskId: 'task-1',
    projectId: 'proj-wms',
    source: 'local',
  },
  {
    id: 'evt-3',
    title: 'Lunch',
    date: today,
    startTime: '13:00',
    endTime: '14:00',
    color: '#64748b',
    taskId: null,
    projectId: null,
    source: 'local',
  },
  {
    id: 'evt-4',
    title: 'Reunión con Pao',
    date: today,
    startTime: '15:00',
    endTime: '16:00',
    color: '#22c55e',
    taskId: 'task-3',
    projectId: 'proj-teopm',
    source: 'local',
  },
  {
    id: 'evt-5',
    title: 'Presentación',
    date: today,
    startTime: '17:00',
    endTime: '18:00',
    color: '#8b5cf6',
    taskId: 'task-5',
    projectId: null,
    source: 'local',
  },
];

export const SEED_TIME_SESSIONS: TimeSession[] = [
  {
    id: 'ts-1',
    taskId: 'task-1',
    projectId: 'proj-wms',
    category: 'Design',
    label: 'Design · WMS',
    startedAt: `${today}T09:00:00.000Z`,
    endedAt: `${today}T10:37:00.000Z`,
    durationSeconds: 97 * 60,
    date: today,
  },
  {
    id: 'ts-2',
    taskId: 'task-2',
    projectId: 'proj-teopm',
    category: 'Marketing',
    label: 'Marketing · TEOPM',
    startedAt: `${today}T07:00:00.000Z`,
    endedAt: `${today}T08:12:00.000Z`,
    durationSeconds: 72 * 60,
    date: today,
  },
  {
    id: 'ts-3',
    taskId: null,
    projectId: 'proj-teopm',
    category: 'TEOPM',
    label: 'TEOPM · General',
    startedAt: `${today}T06:00:00.000Z`,
    endedAt: `${today}T07:00:00.000Z`,
    durationSeconds: 91 * 60,
    date: today,
  },
  {
    id: 'ts-4',
    taskId: 'task-3',
    projectId: 'proj-teopm',
    category: 'Meetings',
    label: 'Meetings · Reunión con Pao',
    startedAt: `${today}T05:00:00.000Z`,
    endedAt: `${today}T06:05:00.000Z`,
    durationSeconds: 65 * 60,
    date: today,
  },
  {
    id: 'ts-5',
    taskId: null,
    projectId: null,
    category: 'Marketing',
    label: 'Marketing · Ads review',
    startedAt: iso(-1) + 'T09:00:00.000Z',
    endedAt: iso(-1) + 'T09:40:00.000Z',
    durationSeconds: 40 * 60,
    date: iso(-1),
  },
];

export const SEED_IDEAS: Idea[] = [
  {
    id: 'idea-1',
    title: 'Concepto para merch de Michiverso',
    description: 'Línea de stickers + pines basada en los personajes principales.',
    tags: ['Merch', 'Ideas'],
    imageUrl: null,
    url: null,
    date: iso(0),
    convertedTo: null,
  },
  {
    id: 'idea-2',
    title: 'Stream: Jochi Horror Nights',
    description: 'Especial de octubre — colaboración con 2 streamers invitados.',
    tags: ['Stream', 'Content'],
    imageUrl: null,
    url: null,
    date: iso(-1),
    convertedTo: null,
  },
  {
    id: 'idea-3',
    title: 'Video para LinkedIn (TEOPM)',
    description: 'Formato talking-head de 60s explicando el caso de éxito del mes.',
    tags: ['Marketing', 'Content'],
    imageUrl: null,
    url: null,
    date: iso(-2),
    convertedTo: null,
  },
];

export const SEED_BOARDS: Board[] = [
  {
    id: 'board-1',
    name: 'WMS LOGO',
    description: 'References, typography, colors, ideas.',
    createdAt: iso(-10),
    items: [
      { id: uuid(), type: 'section', content: 'References', x: 40, y: 40, w: 260, h: 200, color: '#3b82f6' },
      { id: uuid(), type: 'sticky', content: 'Bold geometric sans, monoline mark', x: 60, y: 90, w: 200, h: 120, color: '#3b82f6' },
      { id: uuid(), type: 'section', content: 'Typography', x: 340, y: 40, w: 260, h: 200, color: '#8b5cf6' },
      { id: uuid(), type: 'sticky', content: 'Aeonik / Neue Montreal / Suisse', x: 360, y: 90, w: 200, h: 100, color: '#8b5cf6' },
      { id: uuid(), type: 'section', content: 'Colors', x: 40, y: 280, w: 260, h: 200, color: '#22c55e' },
      { id: uuid(), type: 'sticky', content: '#0B0B10 · #8B5CF6 · #3B82F6', x: 60, y: 330, w: 200, h: 80, color: '#22c55e' },
      { id: uuid(), type: 'section', content: 'Ideas', x: 340, y: 280, w: 260, h: 200, color: '#ec4899' },
      { id: uuid(), type: 'sticky', content: 'Negative space warehouse shape?', x: 360, y: 330, w: 200, h: 100, color: '#ec4899' },
    ],
  },
];

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: uuid(),
    type: 'task_completed',
    message: 'Logo WMS marked as completed',
    timestamp: `${today}T18:00:00.000Z`,
  },
  {
    id: uuid(),
    type: 'idea_added',
    message: 'Added new idea to Ideas Vault — "Concepto para merch de Michiverso"',
    timestamp: `${today}T15:00:00.000Z`,
  },
  {
    id: uuid(),
    type: 'project_updated',
    message: 'Updated project TEOPM — +2 tasks, +1 estimated',
    timestamp: iso(-1) + 'T12:00:00.000Z',
  },
  {
    id: uuid(),
    type: 'settings_updated',
    message: 'You connected Google Calendar',
    timestamp: iso(-1) + 'T09:00:00.000Z',
  },
];

export const SEED_SETTINGS: UserSettings = {
  name: 'Alex St.',
  role: 'Creative Director',
  avatarEmoji: '🧑‍🎨',
  xp: 1240,
  streak: 7,
  lastActiveDate: iso(-1),
  dailyFocusGoalMinutes: 8 * 60,
  theme: 'dark',
  integrations: {
    googleCalendar: { connected: false },
    googleDrive: { connected: false },
    gmail: { connected: false },
  },
};
